
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-3
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-3
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ5Nzc0NzYx","is_bot":false,"login":"Xalex217","name":""},"headRefName":"Aaron-Jokes-Controller","number":29,"title":"Aaron jokes service and controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-3/pull/29"},{"author":{"id":"MDQ6VXNlcjQ5Nzc0NzYx","is_bot":false,"login":"Xalex217","name":""},"headRefName":"Aaron-Jokes","number":28,"title":"Aaron jokes","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-3/pull/28"},{"author":{"id":"U_kgDOB8qE7g","is_bot":false,"login":"tmcanepa","name":"Tyler Canepa"},"headRefName":"TylerC-ZipCode-Controller","number":24,"title":"Add ZipCode Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-3/pull/24"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-HomeController","number":23,"title":"[feat][merge] home controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-3/pull/23"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-Location-b02","number":21,"title":"[feat] [merge] Location controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-3/pull/21"},{"author":{"id":"MDQ6VXNlcjQzNzgzODc3","is_bot":false,"login":"yuxiaolejs","name":"Unics Yu"},"headRefName":"Tianle-Location","number":20,"title":"[feat] [merge] Location service","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-3/pull/20"},{"author":{"id":"U_kgDOB8qE7g","is_bot":false,"login":"tmcanepa","name":"Tyler Canepa"},"headRefName":"TylerC-ZipCode","number":18,"title":"Add ZipCode Service and Controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-3/pull/18"}]
